### ISSUE TITLE
Currently is possible to use only the .sass extension

### ISSUE THREAD

**Issue by spazione** [kandebonfim/itcss_cli#6]
It would be cool have the possibility to use also the .scss extension

**Comment by kandebonfim** [comment]
Wow, that's a nice request!

For now, if you rename the file to use the `.scss` extension, it'll use the correct file name in the import file.

But I'll work on the code to have `scss` file by default. Something like this in the `itcss.yml`, for example:
```
# ========================================
#   #itcss.yml
#   This file is automatically updated by itcsscli.
# ========================================
---
stylesheets_extension: scss
```

And itcsscli would generate all the modules in the right extension.

**Comment by spazione** [comment]
Thanks, it's my first suggestion of my life on github :)

It's not totally clear for me your suggestion. You said to modify the extension of the Manifest.sass to Manifest.scss and after every new module it'll be created and imported with scss extension by itcssCLI. Right ?

Anyway I think I'll wait that you will add this new behaviour. it's perfectly what I was looking for. I can not wait to use i :)

p.s. Great Job!

p.p.s I have another suggestion, maybe is less important but I think it will be cool. I have to open a new Issue?

**Comment by kandebonfim** [comment]
@spazione yeah, please open another issue! Thanks for contributing!

I'm running a hackathon this weekend so I'll probably work on this issue on Monday.

**Comment by spazione** [comment]
@kandebonfim Great!, Thanks man

**Comment by kandebonfim** [comment]
Done ✅

Please make sure you have the last version of itcsscli (currently `itcsscli (0.1.15)`) to take advantage of this feature.

**Comment by kandebonfim** [comment]
@spazione Is this issue solved?

**Comment by spazione** [comment]
Hi @kandebonfim Sorry if I never responded I was very busy. I tried ITCSS 0.1.18 with this configuration:

```yaml
# ========================================
#   #itcss.yml
#   This file is automatically updated by itcsscli.
# ========================================
---
stylesheets_directory: style
stylesheets_import_file: application
extension: scss
```

and when I try to create a module e.g `itcss new trumps pages` the result is:

```bash
.
├── itcss.yml
└── style
    ├── application.sass
    └── trumps
        └── _trumps.pages.sass
```
The extension remains `.sass` :(
